### ISSUE TITLE
Causing Homebridge to crash

### ISSUE THREAD

**Issue by SniperStan** [Caserage/bachome#7]
[12/1/2020, 8:23:34 PM] [Config] Initializing config platform...
[12/1/2020, 8:23:34 PM] [Config] Running in Service Mode
[12/1/2020, 8:23:34 PM] [BAChome ALC] Initializing bachome platform...
[12/1/2020, 8:23:34 PM] [BAChome ALC] Loading accessory from cache: Test 
[12/1/2020, 8:23:34 PM] [BAChome ALC] Restoring existing accessory from cache: Test 
[12/1/2020, 8:23:34 PM] TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (internal/crypto/hash.js:82:11)
    at Object.generate (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:9:11)
    at ExampleHomebridgePlatform.discoverDevices (/homebridge/node_modules/homebridge-bachome/src/platform.ts:69:38)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-bachome/src/platform.ts:43:12)
    at HomebridgeAPI.emit (events.js:327:22)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:251:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:158:14)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
[12/1/2020, 8:23:34 PM] Got SIGTERM, shutting down Homebridge...

**Comment by Apsysikal** [comment]
Hi, thanks for opening an issue.
I am currently not able to actively reproduce the issue.
To me it seems that it's call to

`const uuid = this.api.hap.uuid.generate(device.serial);`

with

`device.serial`

being empty.

Have you deleted the cache? May I also ask how your config file looks?

**Comment by SniperStan** [comment]
I'll have to install it again and get you the info, I had to completely remove it to get homebridge back up and running.

**Comment by Apsysikal** [comment]
I'm closing this issue, as it seems to have gotten stale.
